- hosts: localhost
  name: Snapmirror Create
  gather_facts: false
  vars:
    ontap: &ontap
      hostname:       "{{ netapp_hostname }}"
      username:       "{{ netapp_username }}"
      password:       "{{ netapp_password }}"
      https:          true
      validate_certs: false
  vars_files:
    - var_demo.yml
  collections:
    - netapp.ontap
  tasks:
    - name: Delete cluster peer
      na_ontap_cluster_peer:
        state: absent
        source_cluster_name: "{{ source_cluster_name }}"
        dest_cluster_name: "{{ peer_cluster }}"
        hostname: "{{ src_ontap }}"
        username: "{{ netapp_username }}"
        password: "{{ netapp_password }}"
        peer_options:
          hostname: "{{ peer_cluster }}"

