# cluster management and credentials to access the instances
netapp_hostname: "198.19.254.109"
netapp_username: "fsxadmin"
netapp_password: "Netapp1!"

# Variables to create snapmirror
src_ontap: "{{ netapp_hostname }}"
src_name: skdemo01
src_lif: "10.0.4.8,10.0.5.85"
src_vserver: "svm_{{ src_name }}"
dst_ontap: "198.19.254.66"
dst_name: skdemo02
dst_lif: "10.0.4.85,10.0.5.96"
dst_vserver: "svm_{{ dst_name }}"
passphrase: IamAp483p45a83
peer_cluster: "FsxId092d3dcdeb87ca58b"

# flexcache variables
origin_volume: "vol_skdemo01"
flexcache_volume: "vol_flexcache01"
flexcache_size_gb: 1
# source_cluster_name: "fs-0d9db2c96ed0280a9"